# Generated by Django 2.2.3 on 2019-07-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
